[package]
name = "workshop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "2.1.1"
clap = {version = "3.2.16", features = ["derive"]}
walkdir = "2.3.2"
